### ISSUE TITLE
Fixing the scrolling navbar

### ISSUE THREAD

**Issue by Sheeptune** [Sheeptune/Bacalao#1]
Get circles on both focus and hover status - Have a thinner scrolling navbar (handling with the ul css properties) - White dots everywhere whatever they are selected or not - And a transition effect to shift from one section to another

**Comment by philippepary** [comment]
The goal is to reproduce this scroll : https://landing.adobe.com/en/na/products/marketing-cloud/ctir-3108-running-on-experience/index.html
